backend/controllers/OrderController.php
<?php


namespace backend\controllers;


use backend\models\forms\AddressForm;
use backend\models\forms\PhoneForm;
use backend\models\order\Order;
use backend\models\order\OrderSearchModel;
use backend\models\order\OrderStatus;
use http\Url;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;

class OrderController extends BaseController
{
    public function actionActive()
    {
        $orders = Order::find()->where(['status' => [OrderStatus::STATUS_NEW, OrderStatus::STATUS_COOKING]])->all();
        foreach ($orders as $order)
            $order->setCooking();

        return $this->render('active', ['orders' => $orders]);
    }

    public function actionCooked($id)
    {
        $order = $this->findModel($id);
        $order->setDelivering();

        $this->redirect(['order/active']);
    }

    public function actionNew()
    {
        $model = new PhoneForm();

        if ($model->load(\Yii::$app->request->post()) && $model->validate()){
            $hash = $model->authCustomer();
            $this->redirect(\Yii::$app->params['domens']['ami']."/index.php?hash=".$hash, 301);
        }

        return $this->render('new', ['model' => $model]);
    }

    public function actionPay($id){
        $order = $this->findModel($id);
        $order->pay();

        return $this->redirect(['view', 'id' => $order->id]);
    }

    public function actionPayIndex($id){
        $order = $this->findModel($id);
        if (!$order->paid)
            $order->pay();
        else
            $order->notPay();

        return $this->redirect(['/order/index']);
    }

    public function actionChangePay($id){
        $order = $this->findModel($id);
        $order->changeTypePay();

        return $this->redirect(['view', 'id' => $order->id]);
    }

    public function actionFinish($id){
        $order = $this->findModel($id);
        $order->finish();

        return $this->redirect(['view', 'id' => $order->id]);
    }

    public function actionIndex(){
        $model = new OrderSearchModel();

        if (\Yii::$app->request->isPost)
            $model->load(\Yii::$app->request->post());

        return $this->render('index', ['dataProvider' => $model->search(), 'model' => $model]);
    }

    public function actionView($id){
        $order = $this->findModel($id);
        $address_form = new AddressForm(['order' => $order]);

        if ($address_form->load(\Yii::$app->request->post()) && $address_form->validate())
            $address_form->save();

        if ($order->load(\Yii::$app->request->post()) && $order->validate())
            $order->save();

        return $this->render('view', ['order' => $order, 'address_form' => $address_form]);
    }

    protected function findModel($id)
    {
        $model = Order::findOne($id);

        if (!$model)
            throw new NotFoundHttpException('Данной страницы не существует!');

        return $model;
    }
}

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use backend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--begin::Web font -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({
            google: {"families":["Montserrat:300,400,500,600,700","Roboto:300,400,500,600,700"]},
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <!--end::Web font -->
    <!--begin::Global Theme Styles -->
    <link href="/assets2/vendors/base/vendors.bundle.css" rel="stylesheet" type="text/css" />

    <!--RTL version:<link href="../../../assets/vendors/base/vendors.bundle.rtl.css" rel="stylesheet" type="text/css" />-->
    <link href="/assets2/demo/demo3/base/style.bundle.css" rel="stylesheet" type="text/css" />

    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="m-page--fluid m--skin- m-content--skin-light2 m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default">

<?php $this->beginBody() ?>

<!-- begin:: Page -->
<div class="m-grid m-grid--hor m-grid--root m-page">

    <!-- BEGIN: Header -->
    <header id="m_header" class="m-grid__item m-header " m-minimize-offset="200" m-minimize-mobile-offset="200">
        <div class="m-container m-container--fluid m-container--full-height">
            <div class="m-stack m-stack--ver m-stack--desktop">

                <!-- BEGIN: Brand -->
                <div class="m-stack__item m-brand  m-brand--skin-dark ">
                    <div class="m-stack m-stack--ver m-stack--general">
                        <div class="m-stack__item m-stack__item--middle m-stack__item--center m-brand__logo">
                            <a href="/" class="m-brand__logo-wrapper">
                                <img alt="" src="/img/logo.png" style="width: 40%;"/>
                            </a>
                        </div>
                        <div class="m-stack__item m-stack__item--middle m-brand__tools">

                            <!-- BEGIN: Responsive Aside Left Menu Toggler -->
                            <a href="javascript:;" id="m_aside_left_offcanvas_toggle" class="m-brand__icon m-brand__toggler m-brand__toggler--left m--visible-tablet-and-mobile-inline-block">
                                <span></span>
                            </a>

                            <!-- END -->

                            <!-- BEGIN: Responsive Header Menu Toggler -->
                            <a id="m_aside_header_menu_mobile_toggle" href="javascript:;" class="m-brand__icon m-brand__toggler m--visible-tablet-and-mobile-inline-block">
                                <span></span>
                            </a>

                            <!-- END -->

                            <!-- BEGIN: Topbar Toggler -->
                            <a id="m_aside_header_topbar_mobile_toggle" href="javascript:;" class="m-brand__icon m--visible-tablet-and-mobile-inline-block">
                                <i class="flaticon-more"></i>
                            </a>

                            <!-- BEGIN: Topbar Toggler -->
                        </div>
                    </div>
                </div>

                <!-- END: Brand -->
                <div class="m-stack__item m-stack__item--fluid m-header-head" id="m_header_nav">

                    <!-- BEGIN: Horizontal Menu -->
                    <button class="m-aside-header-menu-mobile-close  m-aside-header-menu-mobile-close--skin-dark " id="m_aside_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
                    <div id="m_header_menu" class="m-header-menu m-aside-header-menu-mobile m-aside-header-menu-mobile--offcanvas  m-header-menu--skin-light m-header-menu--submenu-skin-light m-aside-header-menu-mobile--skin-dark m-aside-header-menu-mobile--submenu-skin-dark ">

                    </div>

                    <!-- END: Horizontal Menu -->

                    <!-- BEGIN: Topbar -->
                    <div id="m_header_topbar" class="m-topbar  m-stack m-stack--ver m-stack--general">
                        <div class="m-stack__item m-topbar__nav-wrapper">
                            <ul class="m-topbar__nav m-nav m-nav--inline">
                                <li class="m-nav__item m-topbar__user-profile m-topbar__user-profile--img m-dropdown m-dropdown--medium m-dropdown--arrow m-dropdown--header-bg-fill m-dropdown--align-right m-dropdown--mobile-full-width m-dropdown--skin-light"
                                    m-dropdown-toggle="click">
                                    <a href="#" class="m-nav__link m-dropdown__toggle">
												<span class="m-topbar__userpic">
													<img src="/img/smail.jpg" alt="" />
												</span>
                                    </a>
                                    <div class="m-dropdown__wrapper">
                                        <span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
                                        <div class="m-dropdown__inner">
                                            <div class="m-dropdown__header m--align-center" style="background: url(/assets2/app/media/img/misc/user_profile_bg.jpg); background-size: cover;">
                                                <div class="m-card-user m-card-user--skin-dark">
                                                    <div class="m-card-user__pic">
                                                        <img src="/img/smail.jpg" alt="" />
                                                    </div>
                                                    <div class="m-card-user__details">
                                                        <span class="m-card-user__name m--font-weight-500"><?=Yii::$app->user->identity->username?></span>
                                                        <a href="" class="m-card-user__email m--font-weight-300 m-link"><?=Yii::$app->user->identity->username?></a>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="m-dropdown__body">
                                                <div class="m-dropdown__content">
                                                    <ul class="m-nav m-nav--skin-light">
                                                        <li class="m-nav__item">
                                                            <a href="<?=\yii\helpers\Url::to(['/site/logout'])?>" class="btn m-btn--pill    btn-secondary m-btn m-btn--custom m-btn--label-brand m-btn--bolder" data-method="post">Выход</a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <!-- END: Topbar -->
                </div>
            </div>
        </div>
    </header>

    <!-- END: Header -->

    <!-- begin::Body -->
    <div class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body">
        <!-- BEGIN: Left Aside -->
        <button class="m-aside-left-close m-aside-left-close--skin-dark" id="m_aside_left_close_btn"><i class="la la-close"></i></button>
        <div id="m_aside_left" class="m-grid__item	m-aside-left  m-aside-left--skin-dark ">
            <?=$this->render('main_menu');?>
        </div>

        <!-- END: Left Aside -->
        <div class="m-grid__item m-grid__item--fluid m-wrapper">
            <!-- BEGIN: Subheader -->
            <div class="m-subheader ">
                <?= Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]) ?>
            </div>

            <!-- END: Subheader -->

            <div class="m-content">
                <?= $content ?>
            </div>
        </div>
    </div>

    <!-- end:: Body -->

    <!-- begin::Footer -->
    <footer class="m-grid__item		m-footer ">
        <div class="m-container m-container--fluid m-container--full-height m-page__container">
            <div class="m-stack m-stack--flex-tablet-and-mobile m-stack--ver m-stack--desktop">
                <div class="m-stack__item m-stack__item--left m-stack__item--middle m-stack__item--last">
							<span class="m-footer__copyright">
								<?=date("Y")?> &copy; Rail Muchametshin
							</span>
                </div>
                <div class="m-stack__item m-stack__item--right m-stack__item--middle m-stack__item--first">
                </div>
            </div>
        </div>
    </footer>

    <!-- end::Footer -->
</div>

<!-- end:: Page -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main_login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use backend\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--begin::Web font -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({
            google: {"families":["Montserrat:300,400,500,600,700","Roboto:300,400,500,600,700"]},
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <!--end::Web font -->

    <!--end::Web font -->
    <!--begin::Global Theme Styles -->
    <link href="/assets2/vendors/base/vendors.bundle.css" rel="stylesheet" type="text/css" />

    <!--RTL version:<link href="../../../assets/vendors/base/vendors.bundle.rtl.css" rel="stylesheet" type="text/css" />-->
    <link href="/assets2/demo/demo3/base/style.bundle.css" rel="stylesheet" type="text/css" />

    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="m-page--fluid m--skin- m-content--skin-light2 m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default">

<?php $this->beginBody() ?>

<!-- begin:: Page -->
<div class="m-grid m-grid--hor m-grid--root m-page">
    <div class="m-grid__item m-grid__item--fluid m-grid m-grid--hor m-login m-login--signin m-login--2 m-login-2--skin-3" id="m_login" style="background-image: url(/assets2/app/media/img//bg/bg-2.jpg);">
        <div class="m-grid__item m-grid__item--fluid	m-login__wrapper">
            <div class="m-login__container">
                <div class="m-login__logo">
                    <a href="#">
                        <img src="/assets2/app/media/img/logos/logo-1.png">
                    </a>
                </div>

                <?=$content;?>
            </div>
        </div>
    </div>
</div>

<!-- end:: Page -->


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main_menu.php
<!-- BEGIN: Aside Menu -->
<?=\backend\components\MenuWidget\Menu::widget([
    'items' => [
        [
            'icon' => 'flaticon-gift',
            'name' => 'Продукт',
            'items' => [
                [
                    'name' => 'Категории',
                    'url' => \yii\helpers\Url::to(['category/index'])
                ]
            ]
        ],
        [
            'icon' => 'flaticon-shopping-basket',
            'name' => 'Заказы',
            'items' => [
                [
                    'name' => 'Новый',
                    'url' => \yii\helpers\Url::to(['/order/new'])
                ],
                [
                    'name' => 'Все',
                    'url' => \yii\helpers\Url::to(['/order'])
                ],
                [
                    'name' => 'Активные',
                    'url' => \yii\helpers\Url::to(['/order/active'])
                ]
            ]
        ],
        [
            'icon' => 'flaticon-star',
            'name' => 'Промо',
            'url' => \yii\helpers\Url::to(['/promotions'])
        ],
        [
            'icon' => 'flaticon-settings',
            'name' => 'Настройки',
            'items' => [
                [
                    'name' => 'СМС',
                    'url' => \yii\helpers\Url::to(['/sms-setting'])
                ],
                [
                    'name' => 'Онлайн оплата',
                    'url' => \yii\helpers\Url::to(['/pay-setting'])
                ]
            ]
        ],
    ]
])?>
<!-- END: Aside Menu -->