backend/controllers/OrderController.php
<?php


namespace backend\controllers;


use backend\models\forms\AddressForm;
use backend\models\forms\PhoneForm;
use backend\models\order\Order;
use backend\models\order\OrderSearchModel;
use backend\models\order\OrderStatus;
use http\Url;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;

class OrderController extends BaseController
{
    public function actionActive()
    {
        $orders = Order::find()->where(['status' => [OrderStatus::STATUS_NEW, OrderStatus::STATUS_COOKING]])->all();
        foreach ($orders as $order)
            $order->setCooking();

        return $this->render('active', ['orders' => $orders]);
    }

    public function actionCooked($id)
    {
        $order = $this->findModel($id);
        $order->setDelivering();

        $this->redirect(['order/active']);
    }

    public function actionNew()
    {
        $model = new PhoneForm();

        if ($model->load(\Yii::$app->request->post()) && $model->validate()){
            $hash = $model->authCustomer();
            $this->redirect(\Yii::$app->params['domens']['ami']."/index.php?hash=".$hash, 301);
        }

        return $this->render('new', ['model' => $model]);
    }

    public function actionPay($id){
        $order = $this->findModel($id);
        $order->pay();

        return $this->redirect(['view', 'id' => $order->id]);
    }

    public function actionPayIndex($id){
        $order = $this->findModel($id);
        if (!$order->paid)
            $order->pay();
        else
            $order->notPay();

        return $this->redirect(['/order/index']);
    }

    public function actionChangePay($id){
        $order = $this->findModel($id);
        $order->changeTypePay();

        return $this->redirect(['view', 'id' => $order->id]);
    }

    public function actionFinish($id){
        $order = $this->findModel($id);
        $order->finish();

        return $this->redirect(['view', 'id' => $order->id]);
    }

    public function actionIndex(){
        $model = new OrderSearchModel();

        if (\Yii::$app->request->isPost)
            $model->load(\Yii::$app->request->post());

        return $this->render('index', ['dataProvider' => $model->search(), 'model' => $model]);
    }

    public function actionView($id){
        $order = $this->findModel($id);
        $address_form = new AddressForm(['order' => $order]);

        if ($address_form->load(\Yii::$app->request->post()) && $address_form->validate())
            $address_form->save();

        if ($order->load(\Yii::$app->request->post()) && $order->validate())
            $order->save();

        return $this->render('view', ['order' => $order, 'address_form' => $address_form]);
    }

    protected function findModel($id)
    {
        $model = Order::findOne($id);

        if (!$model)
            throw new NotFoundHttpException('Данной страницы не существует!');

        return $model;
    }
}

frontend/controllers/OrderController.php
<?php


namespace frontend\controllers;


use common\models\order\OrderPay;
use frontend\components\OnlinePay;
use frontend\components\YandexPay;
use frontend\models\order\AddressOrderModel;
use frontend\models\order\Order;
use Yii;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;


class OrderController extends BaseController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['address'],
                'rules' => [
                    [
                        'actions' => ['address'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }


    public function actionCart()
    {
        $this->bodyParams = "woocommerce-cart";
        $items = \Yii::$app->cart->getAllItemsQuery()->all();

        if (Yii::$app->request->post('promo'))
            Yii::$app->promo->findPromo(Yii::$app->request->post('promo'));

        if (Yii::$app->request->post('resetPromo'))
            Yii::$app->promo->reset();

        if (count($items) == 0)
            return $this->render('no-cart');

        return $this->render('cart', ['items' => $items]);
    }

    public function actionPhone()
    {
        if (!\Yii::$app->user->isGuest)
            $this->redirect(['/order/address']);

        if (\Yii::$app->request->isPost)
        {
            $phone = \Yii::$app->request->post('phone');
            \Yii::$app->phoneConfirmation->getCodeByPhone($phone);
            $this->redirect(['/order/code']);
        }

        return $this->render('phone');
    }

    public function actionCode()
    {
        $error = false;

        if (\Yii::$app->request->isPost)
        {
            $code = \Yii::$app->request->post('code');
            $result = \Yii::$app->phoneConfirmation->confirmByCode($code);

            if ($result === true)
                $this->redirect('/order/address');

            $error = 'Код несоответствует!';
        }

        return $this->render('code', ['error' => $error]);
    }

    public function actionAddress()
    {
        $this->bodyParams = "woocommerce-checkout";
        $items = \Yii::$app->cart->getAllItemsQuery()->all();

        if (count($items) == 0)
            $this->redirect(['/order/cart']);

        $model = new AddressOrderModel();

        if (\Yii::$app->request->isPost && $model->load(\Yii::$app->request->post()))
        {
            $order = $model->formOrder();

            if (\Yii::$app->user->identity->backSession){
                \Yii::$app->user->identity->backSession->delete();
                $url = \Yii::$app->params['domens']['crm']."/order/view?id=".$order->id;
                return $this->redirect($url, 301);
            }elseif ($order->type_pay == Order::TYPE_PAY_CASH)
                $this->redirect(['/order/view', 'id' => $order->id]);
            elseif ($order->type_pay == Order::TYPE_PAY_ELECTRON)
                $this->redirect(['/order/pay', 'id' => $order->id]);
        }

        return $this->render('address', ['items' => $items, 'model' => $model]);
    }

    public function actionView($id)
    {
        $this->bodyParams = "woocommerce-order-received woocommerce-checkout";

        $model = $this->findModel($id);

        return $this->render('view', ['model' => $model]);
    }

    public function actionV($id)
    {
        $this->bodyParams = "woocommerce-order-received woocommerce-checkout";

        $model = $this->findModel($id);

        return $this->render('v', ['model' => $model]);
    }

    public function actionPay($id)
    {
        $order = $this->findModel($id);
        $pay = new OnlinePay();
        $url = $pay->pay($order);

        $this->redirect($url);
    }

    public function actionRaiting($id){
        $order = $this->findModel($id);

        $model = $order->orderRaiting;

        if (!$model)
            return $this->redirect('/');

        if (Yii::$app->request->isPost){
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $model->is_processed = true;
                $model->save();
                $order->deleteOrderLink();
                return $this->redirect(['order/thanks']);
            }
        }

        return $this->render('raiting', ['model' => $model]);
    }

    public function actionThanks(){
        return $this->render('thanks');
    }

    private function findModel($id)
    {
        $model = Order::find()
            ->joinWith('orderCustomer')
            ->where(['Orders.id' => $id])
            ->andWhere(['customer_id' => \Yii::$app->user->id])
            ->one();

        if (!$model)
            throw new NotFoundHttpException('Данной страницы не существует!');

        return $model;
    }

    public function actionSberbank($orderId){
        $order_pay = OrderPay::findOne(['pay_id' => $orderId]);

        if (!$order_pay)
            throw new NotFoundHttpException('no orderId');

        $order = $order_pay->order;

        return $this->redirect(['view', 'id' => $order->id]);
    }
}

backend/views/order/active.php
<?php

/* @var $this \yii\web\View */
/* @var $orders \backend\models\order\Order[] */

$this->title = "Активные заказы";

$script = <<<JS
    function soundClick() {
        var audio = new Audio(); // Создаём новый элемент Audio
        audio.src = '/sounds/sound.mp3'; // Указываем путь к звуку "клика"
        audio.autoplay = true; // Автоматически запускаем
    }
    
    $(document).ready(function() {
        setInterval(function() {
            $.post('/api-order/get-new', function(data) {
                if (data.result != "0"){
                    $.pjax.reload({container:"#pjax-orders"});
                    soundClick();
                }
            });
        }, 3000);
    });
JS;

$this->registerJs($script);

?>

<div>
    <h3><?=$this->title?></h3>

    <? \yii\widgets\Pjax::begin(['id' => 'pjax-orders'])?>

        <?foreach ($orders as $order):?>
            <div class="col-sm-4">
                <div class="card mb-3">
                    <div class="card-header">
                        Заказ №<?=$order->id?>
                    </div>
                    <div class="card-body">
                       <table class="table">
                           <?foreach ($order->orderItems as $item):?>
                               <tr>
                                   <td><b><?=$item->goodFullName?></b></td>
                                   <td><b><?=$item->count?></b></td>
                               </tr>
                           <?endforeach;?>
                       </table>
                        <?=\yii\helpers\Html::a('Готово', \yii\helpers\Url::to(['order/cooked', 'id' => $order->id]), ['class' => 'btn btn-success', 'style' => 'width: 100%;'])?>
                    </div>
                </div>
            </div>


        <?endforeach;?>

    <? \yii\widgets\Pjax::end()?>
</div>

backend/views/order/index.php
<?php
$this->title = 'Заказы';

use yii\grid\ActionColumn;
use yii\grid\GridView; ?>

<div>
    <?$form = \yii\widgets\ActiveForm::begin()?>
        <table class="table">
            <tr>
                <td><?=$form->field($model, "dt_start")->widget(\kartik\date\DatePicker::class, ['options' => ['placeholder' => 'Начало']])->label(false)?></td>
                <td><?=$form->field($model, "dt_end")->widget(\kartik\date\DatePicker::class, ['options' => ['placeholder' => 'Конец']])->label(false)?></td>
                <td><?=$form->field($model, 'type_pay')->widget(\kartik\select2\Select2::class,
                        ['data' => \backend\models\order\Order::getAllPayTypes(), 'options' => ['placeholder' => 'Тип оплаты']])->label(false)?></td>
                <td><?=$form->field($model, 'is_pay')->checkbox()?></td>
                <td><?=\yii\helpers\Html::submitButton('Сформировать', ['class' => 'btn btn-success'])?></td>
            </tr>
        </table>
    <? \yii\widgets\ActiveForm::end()?>
    <hr>
    <h3><?=$this->title?></h3>
    <?=GridView::widget([
        'dataProvider' => $dataProvider,
        'showFooter' => true,
        'columns' => [
            'id',
            'dateCreateText',
            'statusText',
            'orderCustomer.customer.phone',
            'addressText',
            'typePayText',
            'isPayText',
            [
                'attribute' => 'sum',
                'footer' => "<b>".\backend\models\order\OrderSearchModel::getTotalBalance($dataProvider->models, "sum")."</b>"
            ],
            [
                'class' => ActionColumn::class,
                'template' => '{pay}',
                'buttons' => [
                    'pay' => function($url, $model){
                        $text = (!$model->paid)?"Оплачен":"Не оплачен";
                        $class = (!$model->paid)?"success":"danger";
                        return \yii\helpers\Html::a($text, ['/order/pay-index', 'id' => $model->id], ['class' => 'btn btn-'.$class]);
                    }
                ],
                'visibleButtons' => [
                    'pay' => function ($model, $key, $index){
                        return ($model->type_pay == \common\models\order\Orders::TYPE_PAY_CASH)?true:false;
                    }
                ]
            ],
            [
                'class' => ActionColumn::class,
                'template' => '{view}'
            ]
        ]
    ])?>
</div>

backend/views/order/new.php
<?php
$this->title = "Новый заказ";

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput; ?>

<div>
    <h3><?=$this->title?></h3>

    <?$form = ActiveForm::begin(['method' => 'POST'])?>
        <?=$form->field($model, "phone")->widget(MaskedInput::className(), ['mask' => '+7 999 999 9999'])?>
        <?=Html::submitButton('Продолжить', ['class' => 'btn btn-success'])?>
    <? ActiveForm::end()?>
</div>

backend/views/order/view.php
<?php
$this->title = "Заказ №".$order->id;

use backend\models\order\Order;
use common\models\order\OrderStatuses;
use yii\bootstrap\Tabs;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;
use yii\widgets\Pjax; ?>

<div>
    <h3><?=$this->title?></h3>
    <?if ($order->status != OrderStatuses::STATUS_COMPLETE):?>
        <hr>
        <h3>
            Действия
        </h3>
        <?if (!$order->paid):?>
            <?=Html::a('Сменить тип оплаты',['/order/change-pay', 'id' => $order->id], ['class' => 'btn btn-success '])?>
        <?endif;?>
        <?if ($order->type_pay == Order::TYPE_PAY_CASH && !$order->paid):?>
            <?=Html::a('Оплачен',['/order/pay', 'id' => $order->id], ['class' => 'btn btn-success '])?>
        <?endif;?>
        <?=Html::a('Завершен',['/order/finish', 'id' => $order->id], ['class' => 'btn btn-success '])?>
    <?endif;?>
    <hr>
    <?=DetailView::widget([
        'model' => $order,
        'attributes' => [
            'dateCreateText',
            'statusText',
            'orderCustomer.customer.phone',
            'typePayText',
            'isPayText',
            'sum',
            'description'
        ]
    ])?>

    <hr>

    <?$form = ActiveForm::begin(['method' => 'POST'])?>
        <?=$form->field($order, 'sum')?>
        <?=Html::submitButton('Сохранить', ['class' => 'btn btn-success'])?>
    <? ActiveForm::end()?>

    <hr>

    <h3>Адрес</h3>
    <?$form = ActiveForm::begin(['method' => 'POST'])?>
        <?=$form->field($address_form, 'address')?>
        <?=$form->field($address_form, 'place')?>
        <?=Html::submitButton('Сохранить', ['class' => 'btn btn-success'])?>
    <? ActiveForm::end()?>

    <hr>

    <h3>Позиции</h3>
    <div class="gridview-editable">
        <?=GridView::widget([
            'dataProvider' => $order->itemsDataProvider,
            'columns' => [
                'goodFullName',
                'count',
                'price',
                'sum'
            ]
        ])?>
    </div>
</div>